export const FETCH_POST_START = 'FETCH_POST_START';
export const FETCH_POST_ERROR = 'FETCH_POST_ERROR';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const UPDATE_POST_START = 'UPDATE_POST_START';
export const UPDATE_POST_ERROR = 'UPDATE_POST_ERROR';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';
