export const FETCH_POSTS_START = 'FETCH_POSTS_START';
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const DELETE_POST_START = 'DELETE_POST_START';
export const DELETE_POST_ERROR = 'DELETE_POST_ERROR';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
