source 'https://rubygems.org'

gem 'active_model_serializers', '~> 0.10.2'
gem 'bcrypt', '~> 3.1', '>= 3.1.11'
gem 'friendly_id', '~> 5.1'
gem 'jwt', '~> 1.5', '>= 1.5.4'
gem 'kaminari', '~> 0.17.0'
gem 'pg', '~> 0.18.4'
gem 'puma', '~> 3.4'
gem 'rack-cors', '~> 0.4.0'
gem 'rails', '5.0.0'

group :development do
  gem 'listen', '~> 3.0.5'
  gem 'rubocop', '~> 0.41.2', require: false
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :development, :test do
  gem 'database_cleaner', '~> 1.5', '>= 1.5.3'
  gem 'dotenv', '~> 2.1', '>= 2.1.1'
  gem 'guard-rspec', '~> 4.7', '>= 4.7.2', require: false
  gem 'factory_girl_rails', '~> 4.7'
  gem 'rspec-rails', '~> 3.5', '>= 3.5.1'
  gem 'timecop', '~> 0.8.1'
end
