export const SHOW_ALERT = 'SHOW_ALERT';
export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
