export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOCATION_CHANGE = 'LOCATION_CHANGE';
export const AUTHENTICATION_START = 'AUTHENTICATION_START';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
