export const SHOW_ALERT = 'SHOW_ALERT';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';
export const FORGOT_PASSWORD_ATTEMPT = 'FORGOT_PASSWORD_ATTEMPT';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
